try:
    print(x)
except:
    print("something went wrong")
else:
    print("nothing went wrong")
finally:
    print("the 'try except'is finished")    
